#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════
#  MYTH — RPM Package Builder (Fedora / RHEL / CentOS)
#  Produces .rpm packages from pre-compiled binaries and
#  generates createrepo metadata for dnf/yum consumption.
#
#  Usage:
#    bash scripts/build_rpm.sh               # builds x86_64 + aarch64
#    bash scripts/build_rpm.sh x86_64        # builds only x86_64
#    bash scripts/build_rpm.sh --dry-run     # validate spec only
#
#  Requires: rpmbuild (already on Kali), createrepo_c
# ═══════════════════════════════════════════════════════════
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

# ─── Visual Branding ───
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
# CYAN is unused but reserved for tactical consistency
MAGENTA='\033[0;35m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${BLUE}⚡${NC}  ${BOLD}$1${NC}"; }
ok()      { echo -e "${GREEN}✔${NC}  $1"; }
warn()    { echo -e "${YELLOW}⚠  [WARN]${NC}  $1"; }
err()     { echo -e "${RED}✘  [FATAL]${NC} $1"; exit 1; }
section() { echo -e "\n${BOLD}${MAGENTA}─── $1 ───${NC}"; }

# ─── Architecture Map ───
# (Note: Mapped via command line arguments)

# ─── Rust Target Map ───
declare -A RPM_TO_RUST=(
    [x86_64]="x86_64-unknown-linux-gnu"
    [aarch64]="aarch64-unknown-linux-gnu"
    [armv7hl]="armv7-unknown-linux-gnueabihf"
    [i686]="i686-unknown-linux-gnu"
)

# ─── Parse arguments ───
DRY_RUN=false
SIGN_PACKAGE=false
BUILD_ARCHES=()

for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --sign) SIGN_PACKAGE=true ;;
        amd64|x86_64|x64)   BUILD_ARCHES+=("x86_64") ;;
        arm64|aarch64)      BUILD_ARCHES+=("aarch64") ;;
        armhf|armv7hl)      BUILD_ARCHES+=("armv7hl") ;;
        i386|i686)          BUILD_ARCHES+=("i686") ;;
        *)                  warn "Unknown argument: $arg" ;;
    esac
done

# Default: build both primary architectures
if [ ${#BUILD_ARCHES[@]} -eq 0 ]; then
    BUILD_ARCHES=("x86_64" "aarch64")
fi

# ─── Extract metadata from Cargo.toml ───
# Standardized Extraction: Targets the top-level version field from Cargo.toml
MYTH_VERSION=$(sed -n 's/^version[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' Cargo.toml | head -n 1)

DESCRIPTION=$(sed -n 's/^description = "\(.*\)"/\1/p' Cargo.toml | head -n 1)
LICENSE=$(sed -n 's/^license = "\(.*\)"/\1/p' Cargo.toml | head -n 1)
HOMEPAGE=$(sed -n 's/^homepage = "\(.*\)"/\1/p' Cargo.toml | head -n 1)
# REPO_URL is unused but extracted for manifest parity

section "RPM PACKAGE BUILDER"
info "Version: $MYTH_VERSION"
info "Architectures: ${BUILD_ARCHES[*]}"

# ─── Pre-flight checks ───
if ! command -v rpmbuild &>/dev/null; then
    err "rpmbuild not found. Install: sudo apt install rpm"
fi
ok "rpmbuild: $(rpmbuild --version 2>/dev/null | head -1)"

# ─── Ensure createrepo_c is available ───
CREATEREPO_CMD=""
if command -v createrepo_c &>/dev/null; then
    CREATEREPO_CMD="createrepo_c"
elif command -v createrepo &>/dev/null; then
    CREATEREPO_CMD="createrepo"
else
    warn "createrepo_c not found. Will attempt to install..."
    if sudo apt-get install -y -qq createrepo-c 2>/dev/null; then
        CREATEREPO_CMD="createrepo_c"
        ok "createrepo_c installed."
    elif sudo apt-get install -y -qq createrepo 2>/dev/null; then
        CREATEREPO_CMD="createrepo"
        ok "createrepo installed."
    else
        warn "Could not install createrepo. RPM packages will be built but repo metadata will be skipped."
        warn "Install manually: sudo apt install createrepo-c"
    fi
fi

if [ -n "$CREATEREPO_CMD" ]; then
    ok "Repo metadata tool: $CREATEREPO_CMD"
fi

# ─── Setup rpmbuild directory structure ───
RPM_TOPDIR="$(pwd)/target/rpmbuild"
RPM_OUTPUT="$(pwd)/target/rpm"
mkdir -p "$RPM_TOPDIR"/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
mkdir -p "$RPM_OUTPUT"

# ─── Generate spec file ───
SPEC_FILE="$RPM_TOPDIR/SPECS/myth.spec"
info "Generating RPM spec file..."

cat > "$SPEC_FILE" << 'SPECEOF'
# ═══════════════════════════════════════════════════
#  MYTH — RPM Package Specification
#  Auto-generated by scripts/build_rpm.sh
# ═══════════════════════════════════════════════════
Name:           myth
Version:        __VERSION__
Release:        1%{?dist}
Summary:        __DESCRIPTION__
License:        __LICENSE__
URL:            __HOMEPAGE__
Source0:        myth

# Disable debug package generation (we ship pre-stripped binaries)
%define debug_package %{nil}
# Disable binary stripping (already stripped by cargo)
%define __strip /bin/true
# Disable build-id links (pre-compiled binary)
%define _build_id_links none

# ─── Dependencies ───
# Core system libraries
Requires:       glibc >= 2.31
Requires:       openssl-libs
Requires:       ca-certificates
Requires:       zstd

# Sandbox (critical for MYTH's security model)
Requires:       bubblewrap >= 0.6

# Essential recon tools (available in standard Fedora/RHEL repos)
Requires:       nmap
Requires:       curl
Requires:       git
Requires:       wget
Requires:       whois

# Weak dependencies (recommended but not required)
Recommends:     tor

%description
MYTH is an ultra-powerful, tactical AI reconnaissance agent designed for
high-fidelity asset discovery and attack surface mapping. It features a
unified neural link system with persistent session memory, sandboxed
execution via Bubblewrap, and advanced MCP tool discovery.

%install
mkdir -p %{buildroot}/usr/bin
mkdir -p %{buildroot}/etc/myth
mkdir -p %{buildroot}/usr/share/doc/myth
mkdir -p %{buildroot}/usr/share/man/man1
mkdir -p %{buildroot}/usr/share/bash-completion/completions
mkdir -p %{buildroot}/usr/share/zsh/site-functions
mkdir -p %{buildroot}/usr/share/fish/vendor_completions.d

# Binary
cp %{SOURCE0} %{buildroot}/usr/bin/myth
chmod 755 %{buildroot}/usr/bin/myth

# Configuration
cp __PROJECT_ROOT__/config/user.yaml %{buildroot}/etc/myth/user.yaml

# Documentation
cp __PROJECT_ROOT__/README.md %{buildroot}/usr/share/doc/myth/
cp __PROJECT_ROOT__/LICENSE %{buildroot}/usr/share/doc/myth/

# Man page
cp __PROJECT_ROOT__/docs/myth.1 %{buildroot}/usr/share/man/man1/myth.1
gzip -f %{buildroot}/usr/share/man/man1/myth.1

# Shell completions
cp __PROJECT_ROOT__/completions/myth %{buildroot}/usr/share/bash-completion/completions/myth 2>/dev/null || true
cp __PROJECT_ROOT__/completions/_myth %{buildroot}/usr/share/zsh/site-functions/_myth 2>/dev/null || true
cp __PROJECT_ROOT__/completions/myth.fish %{buildroot}/usr/share/fish/vendor_completions.d/myth.fish 2>/dev/null || true

%post
# Post-install: create symlinks
ln -sf /usr/bin/myth /usr/bin/agent 2>/dev/null || true

# Provision Lightpanda browser engine (silent, non-blocking)
if ! command -v lightpanda >/dev/null 2>&1 && [ ! -f /usr/local/bin/lightpanda ]; then
    echo "Provisioning Lightpanda browser engine for MYTH..."
    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64) BINARY="lightpanda-x86_64-linux" ;;
        aarch64) BINARY="lightpanda-aarch64-linux" ;;
        *) BINARY="" ;;
    esac
    if [ -n "$BINARY" ]; then
        TEMP="${TMPDIR:-/tmp}/lightpanda_rpm_$$.tmp"
        URL="https://github.com/lightpanda-io/browser/releases/download/nightly/${BINARY}"
        if curl -fsSL --connect-timeout 15 --max-time 120 "$URL" -o "$TEMP" 2>/dev/null; then
            FILE_SIZE=$(stat -c%s "$TEMP" 2>/dev/null || echo 0)
            if [ "$FILE_SIZE" -gt 10240 ]; then
                chmod +x "$TEMP"
                mv "$TEMP" /usr/local/bin/lightpanda
                echo "Lightpanda engine provisioned."
            else
                rm -f "$TEMP"
            fi
        else
            rm -f "$TEMP" 2>/dev/null || true
        fi
    fi
fi

echo "MYTH Tactical Deployment Complete."

%preun
# Clean up symlinks on uninstall
if [ "$1" -eq 0 ]; then
    rm -f /usr/bin/agent 2>/dev/null || true
fi

%files
%attr(755, root, root) /usr/bin/myth
%config(noreplace) /etc/myth/user.yaml
%doc /usr/share/doc/myth/README.md
%license /usr/share/doc/myth/LICENSE
/usr/share/man/man1/myth.1.gz
%dir /usr/share/bash-completion
%dir /usr/share/bash-completion/completions
%dir /usr/share/zsh
%dir /usr/share/zsh/site-functions
%dir /usr/share/fish
%dir /usr/share/fish/vendor_completions.d
%ghost /usr/share/bash-completion/completions/myth
%ghost /usr/share/zsh/site-functions/_myth
%ghost /usr/share/fish/vendor_completions.d/myth.fish

%changelog
* __DATE__ myth-tools <shesher0llms@gmail.com> - __VERSION__-1
- Release v__VERSION__
SPECEOF

# ─── Replace placeholders in spec ───
PROJECT_ROOT=$(pwd)
CHANGELOG_DATE=$(date '+%a %b %d %Y')
sed -i \
    -e "s|__VERSION__|$MYTH_VERSION|g" \
    -e "s|__DESCRIPTION__|$DESCRIPTION|g" \
    -e "s|__LICENSE__|$LICENSE|g" \
    -e "s|__HOMEPAGE__|$HOMEPAGE|g" \
    -e "s|__PROJECT_ROOT__|$PROJECT_ROOT|g" \
    -e "s|__DATE__|$CHANGELOG_DATE|g" \
    "$SPEC_FILE"

ok "Spec file generated: $SPEC_FILE"

if [ "$DRY_RUN" = true ]; then
    info "[DRY-RUN] Spec file validated. No packages built."
    cat "$SPEC_FILE"
    exit 0
fi

# ─── Build RPM for each architecture ───
PRODUCED_RPMS=()

for RPM_ARCH in "${BUILD_ARCHES[@]}"; do
    section "Building RPM for: $RPM_ARCH"

    RUST_TARGET="${RPM_TO_RUST[$RPM_ARCH]:-}"
    if [ -z "$RUST_TARGET" ]; then
        warn "No Rust target mapping for $RPM_ARCH. Skipping."
        continue
    fi

    # ─── Locate the pre-compiled binary ───
    BINARY_PATH=""
    HOST_ARCH=$(uname -m)

    if [ "$RPM_ARCH" = "$HOST_ARCH" ]; then
        # Host architecture: use native build
        BINARY_PATH="target/release/myth"
    else
        # Cross-compiled: look in cross-compile output
        BINARY_PATH="target/$RUST_TARGET/release/myth"
    fi

    if [ ! -f "$BINARY_PATH" ]; then
        warn "Binary not found at $BINARY_PATH. Run cross_build.sh first. Skipping $RPM_ARCH."
        continue
    fi

    ok "Binary found: $BINARY_PATH ($(du -h "$BINARY_PATH" | cut -f1))"

    # ─── Copy binary to architecture-specific SOURCE ───
    # To prevent race conditions/overwrites in multi-arch runs
    SPEC_ARCH_FILE="$RPM_TOPDIR/SPECS/myth-${RPM_ARCH}.spec"
    cp "$SPEC_FILE" "$SPEC_ARCH_FILE"
    
    # Use unique source name per arch
    ARCH_SOURCE="myth-${RPM_ARCH}"
    cp "$BINARY_PATH" "$RPM_TOPDIR/SOURCES/$ARCH_SOURCE"
    sed -i "s/^Source0:.*/Source0: $ARCH_SOURCE/" "$SPEC_ARCH_FILE"

    # ─── Build the RPM ───
    info "Packaging RPM for $RPM_ARCH..."

    rpmbuild --define "_topdir $RPM_TOPDIR" \
             --define "_arch $RPM_ARCH" \
             --target "$RPM_ARCH" \
             -bb "$SPEC_ARCH_FILE" 2>&1 | tail -5

    # ─── Collect produced RPMs ───
    FOUND_RPM=$(find "$RPM_TOPDIR/RPMS/$RPM_ARCH" -name "myth-*.rpm" -print 2>/dev/null | sort -rV | head -1 || true)

    if [ -z "$FOUND_RPM" ]; then
        warn "No RPM produced for $RPM_ARCH. Check rpmbuild output above."
        continue
    fi

    # ─── Sign the RPM if requested ───
    if [ "$SIGN_PACKAGE" = true ]; then
        info "Signing RPM for $RPM_ARCH..."
        # Requires %_gpg_name in ~/.rpmmacros
        rpmsign --addsign "$FOUND_RPM" &>/dev/null || warn "RPM signing failed. Ensure GPG keys are configured."
    fi

    # ─── Copy to output directory with arch subdirectory ───
    mkdir -p "$RPM_OUTPUT/$RPM_ARCH"
    cp "$FOUND_RPM" "$RPM_OUTPUT/$RPM_ARCH/"
    DEST_RPM="$RPM_OUTPUT/$RPM_ARCH/$(basename "$FOUND_RPM")"
    ok "RPM produced: $DEST_RPM ($(du -h "$DEST_RPM" | cut -f1))"
    PRODUCED_RPMS+=("$DEST_RPM")
done

# ─── Generate repository metadata ───
if [ -n "$CREATEREPO_CMD" ] && [ ${#PRODUCED_RPMS[@]} -gt 0 ]; then
    section "GENERATING RPM REPOSITORY METADATA"
    info "Running $CREATEREPO_CMD on $RPM_OUTPUT..."
    $CREATEREPO_CMD "$RPM_OUTPUT" 2>&1 | tail -5
    ok "RPM repository metadata generated at $RPM_OUTPUT/repodata/"
else
    if [ ${#PRODUCED_RPMS[@]} -gt 0 ]; then
        warn "Skipping repo metadata (createrepo not available)."
    fi
fi

# ─── Summary ───
section "RPM BUILD SUMMARY"

if [ ${#PRODUCED_RPMS[@]} -eq 0 ]; then
    err "No RPM packages produced. Check logs above."
fi

for rpm in "${PRODUCED_RPMS[@]}"; do
    ok "Ready: $rpm"
done

echo ""
echo -e "${GREEN}${BOLD}  ✅ RPM build complete. ${#PRODUCED_RPMS[@]} package(s) ready.${NC}"
echo ""
